application.title=Movie Mux
application.version=1.0
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.include-message=always
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
spring.data.web.pageable.max-page-size=50
kit.key=${KIT_KEY}
kit.url=${KIT_URL}
send.mail=${CINE_SEND_MAIL}
mail.url=${MOVIEMUX_MAIL_URL}
scheduling.enabled=true
discord.webhook.url=${DISCORD_WEBHOOK_URL}
discord.webhook.execute=${DISCORD_WEBHOOK_EXECUTE}
discord.webhook.update=${DISCORD_WEBHOOK_UPDATE}
discord.webhook.role.id=${DISCORD_WEBHOOK_ROLE_ID}
socket.io.api.url=${SOCKET_IO_API_URL}
socket.io.api.key=${SOCKET_IO_API_KEY}
spring.data.web.pageable.one-indexed-parameters=true
management.endpoints.web.exposure.include=health
server.servlet.context-path=/api/monolith
server.port=${PORT:8080}
